# Generated by Django 5.2.4 on 2025-07-23 09:27

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='content',
        ),
        migrations.AddField(
            model_name='article',
            name='ontent',
            field=tinymce.models.HTMLField(default=1),
            preserve_default=False,
        ),
    ]
