# Generated by Django 5.2.4 on 2025-07-23 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_article_content_article_ontent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='ontent',
            new_name='content',
        ),
    ]
