# Generated by Django 5.2.4 on 2025-07-23 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_ontent_article_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('angkatan', models.CharField(max_length=10)),
                ('jabatan', models.CharField(choices=[('ketua', 'Ketua'), ('sekretaris', 'Sekretaris'), ('anggota', 'Anggota')], max_length=20)),
            ],
        ),
    ]
