# Generated by Django 5.2.4 on 2025-07-23 23:23

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_teammember_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='content',
            field=tinymce.models.HTMLField(),
        ),
    ]
